name: Build with custom argument

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-with-build-arg:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and publish Docker Images to GitHub Container registry
      uses: VaultVulp/gp-docker-action@0545b97dff46befac17d3267d3d108eadd4bf1e7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages      
        image-name: my-cool-service # Provide Docker image name
        custom-args: --build-arg=SOME_BUILD_ARG="NEW-VALUE" --build-arg=APP_BUILD_RUNTIME="linux-arm" --build-arg=DOCKER_BUILD_RUNTIME="mcr.microsoft.com/dotnet/runtime:6.0.3-bullseye-slim-arm64v8" --build-arg=DOCKER_BUILD_SDK="mcr.microsoft.com/dotnet/sdk:6.0.201-bullseye-slim-arm64v8"
 # Pass "NEW VALUE" into the SOME_BUILD_ARG
